# Atlas configuration — CONTROL PLANE
# !! DO NOT edit this file in automated migration tasks or agent workflows !!
#
# The primary destructive-change gate is scripts/check-migrations.sh (CI).
# This file exists for local atlas usage (atlas migrate diff, apply, etc.)
# and for future Atlas Pro integration.
#
# NOTE: atlas migrate lint became Atlas Pro-only in v0.38. The open-source
# gate is implemented in scripts/check-migrations.sh instead.

env "ci" {
  dev = "docker://postgres/16/dev?search_path=public"
  migration {
    dir = "file://drizzle/migrations"
  }
}
