# Atlas configuration — CONTROL PLANE
# !! DO NOT edit this file in automated migration tasks or agent workflows !!
# Weakening lint.destructive.force = true would silently remove the hard
# block on data-destroying schema changes.

lint {
  # force = true means this check ALWAYS runs and ALWAYS fails the build.
  # An explicit atlas:nolint directive cannot suppress it.
  destructive {
    force = true
  }
}
